spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

    # 域名检测，启用时将进行解析以验证域名有效性
    # 注意: 开启此功能可能导致处理时间大幅延长
    domain-detect:
      enable: true
      timeout: 30

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
#      - name: 'Subscription 1'               #可选参数: 规则名称，如无将使用 path 作为名称
#        path: 'https://example.org/rule.txt' #必要参数: 规则url，仅支持 http/https，不限定响应内容格式
#       type: easylist                       #可选参数: 规则类型：easylist (默认)、dnsmasq、clash、smartdns、hosts

#    - name: 'Subscription 2'
#       path: 'http://example.org/rule.txt'
      - name: 217heidai聚合
        path: https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt
        type: easylist

      - name: AdGuard 移动广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
        type: easylist

      - name: AdGuard 防跟踪保护过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
        type: easylist

      - name: AdGuard URL跟踪过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt
        type: easylist

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        type: easylist

      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt
        type: easylist

      - name: NoAppDownload
        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt
        type: easylist

      - name: Cats-Team AdBlock List plus
        path: https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock_plus.txt
        type: easylist

      - name: hagezi/dns-blocklists pro
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt
        type: easylist

      - name: xndeye web-ad-rule
        path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt
        type: easylist
        
      - name: adgk手机去广告规则
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
        type: easylist      
        
      - name: 百度搜索结果极限净化
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
        type: easylist   
        
      - name: 晴雅AdGuard订阅规则DNS
        path: http://rssv.cn/adguard/api.php?type=dns
        type: easylist           
        
      - name: 晴雅AdGuard订阅规则HOST
        path: http://rssv.cn/adguard/api.php?type=host
        type: hosts    
        
      - name: 乘风视频过滤规则
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
        type: easylist      
        
      - name: GoodbyeAds-YouTube-AdBlock
        path: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
        type: hosts
        
      - name: adblock_privacy
        path: https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_privacy.txt
        type: easylist         
        
      - name: httpdns block
        path: https://raw.githubusercontent.com/Womsxd/MyAdBlockRules/refs/heads/master/httpdnsblock.txt
        type: easylist           
        
      - name: p2pcdn block
        path: https://raw.githubusercontent.com/Womsxd/MyAdBlockRules/refs/heads/master/p2pcdnblock.txt
        type: easylist     
        
      - name: ProgramAD
        path: https://raw.githubusercontent.com/earoftoast/clash-rules/main/ProgramAD.yaml
        type: clash        


        

    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)
    file_header: |
      Title: Lknife_AD规则整合
      Description:${desc}
      Last Modified: ${date}
      Homepage: https://github.com/Lknife666/Ad_Filter/tree/v2

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进，且每个类型只能输出一个文件）
    files:
      - name: easylist.txt     #必要参数: 文件名
        type: easylist         #必要参数: 文件类型: easylist、dnsmasq、clash、smartdns、hosts
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'  #可选参数: 文件描述，可在file_header中通过 ${} 中使用
        filter:
          - basic              #基本规则，不包含任何控制、匹配符号, 可以转换为 hosts
          - wildcard           #通配规则，仅使用通配符
          - unknown            #其他规则，如使用了正则、高级修饰符号等，这表示目前无法支持

      - name: dns.txt
        type: easylist
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'
        filter:
          - basic
          - wildcard

      - name: dnsmasq.txt
        type: dnsmasq
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'

      - name: clash.yaml
        type: clash
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'

      - name: smartdns.txt
        type: smartdns
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'

      - name: hosts.txt
        type: hosts
        desc: '规则源：1Hosts (Lite)、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist、AWAvenue Ads Rule、jiekouAD、晴雅、Adguard、AGDK、xndeye、乘风、Noyllopa、Cats-Team、hagezi、大圣净化多个上游'
